stages:
  - lint
  - build
  - test

variables:
  IMAGE_DEV: ${CI_REGISTRY_IMAGE}:develop

# Lint stage
#############
.lint-default: &lint-default
  stage: lint
  needs: []
  image: python:3.8
  tags:
    - docker

Pre-commit:
  <<: *lint-default
  stage: lint
  before_script:
    - pip install pre-commit && pre-commit install
  script:
    - pre-commit run --all-files --verbose

Lint Dockerfiles:
  <<: *lint-default
  image: hadolint/hadolint:latest-debian
  before_script:
    - apt-get -y update
    - apt-get -y install --no-install-recommends git
  script:
    - git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 hadolint

# Build stage
#############

Build image:
  stage: build
  needs: []
  dependencies: []
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    entrypoint: [""]
  script:
    # Login to GitLab registry
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --cache
      --context=$CI_PROJECT_DIR
      --dockerfile=$CI_PROJECT_DIR/docker/Dockerfile
      --destination=${IMAGE_DEV}

# Test stage
############
.test-default: &test-default
  stage: test
  dependencies: []

Unittest:
  <<: *test-default
  needs: ["Build image"]
  image: ${IMAGE_DEV}
  script:
    - cd /app && python -m unittest
