repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.1.2
    hooks:
      - id: reuse

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: "tenQ.egg-info/"
      - id: trailing-whitespace
        exclude: "tenQ.egg-info/"

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [ push ]
