# SPDX-FileCopyrightText: 2024 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

services:
  test:
    container_name: 10q
    image: 10q:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src/:/app:rw
      - ./coverage-results/:/coverage-results/:rw
